spring.application.name=werkstuk-entreprise-application
# H2 database
spring.datasource.url=jdbc:h2:mem:ngodb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

# H2 console (handig om je tabellen te bekijken via browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mailtrap SMTP (maak gratis account op mailtrap.io)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=JOUW_MAILTRAP_USERNAME
spring.mail.password=JOUW_MAILTRAP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true